Fix: Add check on impressionData
Unleash/unleash-client-node pull request #434
Opened 2023-03-02 17:17 UTC by dev-dennis-guye

## About the changes

[Impression Data](https://docs.getunleash.io/reference/impression-data) is an opt-in feature. However, the previous implementation triggered events regardless of the status of the impressionData field. This fix adds a simple check on the status of the impressionData field on FeatureInterface before triggering the event.

### Important files'

src/client.ts

## Discussion points

This fix addresses that issue however is more invasive than I would prefer. The change required making an update to the interface of the resolve variant function.

2023-03-03 08:28 UTC, FredrikOseberg approved these changes
LGTM, could you run lint:fix to get the correct formatting. Also, the tests are currently timing out in CI.

2023-03-06 14:32 UTC, dev-dennis-guye commented
> LGTM, could you run lint:fix to get the correct formatting. Also, the tests are currently timing out in CI.

So I took a look, my hypothesis is that this was caused by 

```typescript
client.on(UnleashEvents.Impression, ()=> {
    t.pass()
  });
```

My guess is that Ava expects t.pass() to be the last function executed. I've reimplemnted the tests to instead perform

```typescript
let called=false; 
//code
client.on(UnleashEvents.Impression, ()=> {
    called=true;
  });
//code 
t.true(called); 
```

2023-03-08 14:15 UTC, dev-dennis-guye commented
@FredrikOseberg Any update on this?

2023-03-08 18:06 UTC, FredrikOseberg commented
Hey, thanks for the prompt. I will have another look tomorrow

2023-03-09 13:42 UTC, FredrikOseberg commented
> Details

@dev-dennis-guye Hm. Looks like the tests are timing out here in CI.

2023-03-10 08:58 UTC, Tymek approved these changes

2023-03-10 09:03 UTC, Tymek requested changes

2023-03-10 09:03 UTC, Tymek commented on test/client.test.js
> +function buildToggle(name, active, strategies, variants = [], impressionData= false) {
Looks like a missing space before `=`. I don't know if prettier is working correctly.

2023-03-10 15:47 UTC, dev-dennis-guye commented on test/client.test.js
> +function buildToggle(name, active, strategies, variants = [], impressionData= false) {
```suggestion
function buildToggle(name, active, strategies, variants = [], impressionData = false) {
```

I'm assuming this is the correct formatting.

2023-03-13 07:54 UTC, FredrikOseberg commented
@dev-dennis-guye It looks like your tests are timing out in CI. You might need to make this an async function and use promises to make sure your callback is being called.

<img width="950" alt="Skjermbilde 2023-03-13 kl  08 53 41" src="https://user-images.githubusercontent.com/16081982/224639656-44882cf8-5990-49e0-be3c-979ba7bb9044.png">

2023-03-21 09:43 UTC, FredrikOseberg commented
@dev-dennis-guye You still around?

2023-03-21 13:44 UTC, FredrikOseberg commented
> > @dev-dennis-guye You still around?
> 
> @FredrikOseberg Sorry for the late update. This is is not a promise issue and is also unrelated to the listener remaining attached at the end of the test.

Yeah. My guess is that the tests that were testing this functionality is now hanging because of the added check.

2023-03-22 12:39 UTC, FredrikOseberg approved these changes
LGTM

2023-03-22 12:40 UTC, merged